### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by danielbogart** [rkho/product-hunt-react-native#127]
When I first run the build, I get the error "Could not connect to development server. Ensure node server is running and available on the same network - run 'npm start' from react-native root. When I run npm-start, I'm getting an error about a missing start script, which I assume should be present in package.json.
Here's my npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/bin/iojs',
1 verbose cli   '/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.13.2
3 info using node@v2.5.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /Users/MasterBogart/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
5 verbose cwd /Users/MasterBogart/Documents/coding/ios-apps/projects/product-hunt-react-native
6 error Darwin 14.1.0
7 error argv "/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/MasterBogart/.nvm/versions/io.js/v2.5.0/bin/npm" "start"
8 error node v2.5.0
9 error npm  v2.13.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by danielbogart** [comment]
Solved this issue, it had to do with watchman not working properly and crashing the react packager. Solution was:

`brew uninstall watchman`
`brew install --HEAD watchman`
